name: Build

on:
  workflow_call:
    inputs:
      build_type:
        description: "Build configuration (Debug, Release, or both)"
        type: string
        default: '"Debug","Release"'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        framework: [android, glfw, macos, ios]
        build_type: ${{ fromJSON(format('[{0}]', inputs.build_type)) }}
        exclude:
          - os: windows-latest
            framework: macos
          - os: windows-latest
            framework: android
          - os: windows-latest
            framework: ios
          - os: ubuntu-latest
            framework: macos
          - os: ubuntu-latest
            framework: ios
          - os: ubuntu-latest
            framework: glfw
          - os: macos-latest
            framework: android
      max-parallel: 16

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        id: setup-environment
        uses: ./.github/actions/setup-environment
        with:
          framework: ${{ matrix.framework }}
          os: ${{ matrix.os }}

      - name: Setup Signing Certificates (iOS)
        if: matrix.framework == 'ios'
        uses: ./.github/actions/setup-certs-ios
        with:
          certificate-p12-base64: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE_P12_BASE64 }}
          certificate-password: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
          appstore-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          appstore-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          appstore-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Build
        run: python3 build.py --framework ${{ matrix.framework }} --config ${{ matrix.build_type }} --archive ${{ steps.setup-environment.outputs.build-args }}

      - name: Archive App Bundle (macOS)
        if: matrix.framework == 'macos'
        uses: ./.github/actions/archive-macos
        with:
          certificate-p12-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          certificate-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
          signing-identity: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          notarization-username: ${{ secrets.APPLE_NOTARIZATION_USERNAME }}
          notarization-password: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
          team-id: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
          app-path: build_system/${{ matrix.framework }}/product/${{ matrix.framework }}-macos-${{ matrix.build_type }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}-${{ matrix.os }}-${{ matrix.build_type }}
          path: build_system/${{ matrix.framework }}/product
